//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDatabase.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcategoryProperty : BaseEntity
    {
        public int Id { get; set; }
        public int SubcategoryID { get; set; }
        public int PropertyID { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
